# Dockerized infrastructure
sudo: false
language: python

# Cache SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Decrypt
before_install:
- openssl aes-256-cbc -K $encrypted_e024391c3189_key -iv $encrypted_e024391c3189_iv -in ci.tar.enc -out ci.tar -d
- tar xvf ci.tar

# Docker to build image
services:
  - docker

# Environment
env:
  global:
    - GOOGLE_DEPLOY_CREDENTIALS=~/deploy/deploy-credentials.json
    - GOOGLE_SERVICE_CREDENTIALS=~/deploy/service-credentials.json
    - CLOUDSDK_COMPUTE_ZONE=us-central1-c
    - PROJECT_NAME=poe-analysis-gcs
    - DOCKER_IMAGE=stash-downloader
    - SERVICE_INSTANCE_NAME=stash-downloader

install:
  -

script:
  -

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update

deploy:
  - provider: script
    script: ./deploy/production.sh
    skip_cleanup: true
    on:
      branch: master